addons:
  postgresql: '9.3'
branches:
  only:
  - master
install:
- MIX_ENV=test bin/setup
language: elixir
notifications:
  email: false
  slack:
    secure: WzgbZxJJRmbZ+DjmL/tQ0WdtDogqO0aAOg6Ziv0pvGK6+A/uNmIheVXvoLQQjhuRgz2B7Rj5vB1HioKkR4WodEbf7efnJBXlifOOGLBQZvRlbXPcQgV0TNjcu6wQpltZ5vpXuIzGH934eIesNOlikcnrRZeDVmM+sON/+q6+1bQ=
otp_release:
- 17.4
sudo: false
